// Sarideo UI: ekranlarni chizish va foydalanuvchi holatini boshqarish.
(function (root) {
  'use strict';
  const labels = { director: 'Director · ssenariy', imagesmith: 'Imagesmith · rasmlar', choreographer: 'Choreographer · sahna', subtitler: 'Subtitler · subtitr', publisher: 'Publisher · metadata', rewriter: 'Rewriter · yakunlash' };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const el = id => document.getElementById(id);
  const UI = {
    state: { screen: 'create', project: null },
    toast(message) { const node = el('toast'); node.textContent = message; node.classList.add('is-visible'); clearTimeout(this.toastTimer); this.toastTimer = setTimeout(() => node.classList.remove('is-visible'), 2600); },
    showScreen(name) { this.state.screen = name; document.querySelectorAll('.screen').forEach(s => s.classList.toggle('is-active', s.dataset.screen === name)); document.querySelectorAll('.nav-item').forEach(n => n.classList.toggle('is-active', n.dataset.nav === name)); el('app-main').scrollTop = 0; if (name === 'library') this.renderLibrary(); if (name === 'create') this.renderRecent(); if (name === 'settings') this.loadSettings(); },
    renderRecent() { const list = Store.listProjects().sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 3); el('recent-projects').innerHTML = list.length ? list.map(p => `<article class="project-card" data-project="${esc(p.id)}"><div class="project-card-title">${esc(p.title || p.topic)}</div><div class="project-card-meta">${esc(p.format || 'Shorts · 9:16')} · ${p.scenes?.length || 0} sahna</div></article>`).join('') : '<div class="muted-note">Hali loyiha yo‘q. Birinchi videongizni yarating.</div>'; },
    renderLibrary() { const list = Store.listProjects().sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt)); el('library-list').innerHTML = list.length ? list.map(p => `<article class="library-item" data-project="${esc(p.id)}"><div class="project-card-title">${esc(p.title || p.topic)}</div><div class="project-card-meta">${new Date(p.createdAt).toLocaleDateString('uz-UZ')} · ${p.scenes?.length || 0} sahna · ${p.demo ? 'Demo' : 'API'}</div></article>`).join('') : '<div class="empty-state"><div class="empty-icon">▤</div><h2>Arxiv bo‘sh</h2><p>Yaratilgan loyihalar shu yerda telefonda saqlanadi.</p></div>'; },
    renderStudio(project) { this.state.project = project; el('studio-empty').classList.toggle('is-hidden', !!project); const content = el('studio-content'); content.classList.toggle('is-hidden', !project); if (!project) return; const agents = Object.entries(project.agents || {}).map(([key, value]) => `<div class="pipeline-step"><span class="pipeline-step-title">${labels[key] || key}</span><span class="pipeline-badge ${esc(value.status)}">${value.status === 'done' ? 'Tayyor' : value.status === 'error' ? 'Xato' : value.status === 'running' ? 'Ishlamoqda' : 'Navbatda'}</span></div>`).join(''); const scenes = (project.scenes || []).map((s, i) => `<article class="scene-item"><div class="scene-header"><span class="scene-number">${String(i+1).padStart(2,'0')}</span><span class="scene-duration">${esc(s.duration)} sek</span></div><div class="scene-title">${esc(s.title)}</div><p class="scene-narration">${esc(s.finalNarration || s.narration)}</p><div class="scene-meta">▧ Rasm prompti tayyor · ◌ Ovoz navbatda · Aa Subtitr tayyor</div></article>`).join(''); content.innerHTML = `<div class="studio-hero"><div class="preview-frame"><span>▶</span><small>PREVIEW</small></div><div><h2>${esc(project.title || project.topic)}</h2><p>${esc(project.metadata?.description || 'AI agentlar tayyorlagan video loyihasi')}</p><div class="chosen-options"><span>${esc(project.format || 'Shorts · 9:16')}</span><span>${esc(project.duration || 60)} sek</span><span>${esc(project.voice || 'Ovoz')}</span><span>${esc(project.visualStyle || 'Uslub')}</span></div></div></div><div class="pipeline-card"><div class="card-heading"><strong>Agentlar oqimi</strong><span class="status-text">${project.demo ? 'Demo rejim' : 'API rejim'}</span></div>${agents}</div><div class="section-heading"><h2>${project.scenes?.length || 0} ta sahna</h2><button class="secondary-button" data-action="export">MP4 eksport</button></div><div class="scenes-grid">${scenes}</div><div class="notice"><span>◌</span><p>Rasm, ovoz va MP4 montaj telefondagi WebView imkoniyatiga bog‘liq. Preview tayyor; codec qo‘llanmasa, sabab shu yerda ko‘rsatiladi.</p></div>`; },
    loadSettings() { const s = Store.getSettings(); el('gemini-key').value = s.geminiKey || ''; el('openai-key').value = s.openaiKey || ''; el('openai-endpoint').value = s.openaiEndpoint || 'https://api.openai.com/v1/chat/completions'; el('gemini-status').textContent = s.geminiKey ? 'Ulangan' : 'Ulanmagan'; },
    openProject(id) { const p = Store.getProject(id); if (p) { this.renderStudio(p); this.showScreen('studio'); } },
    async createProject(topic, formOptions) { const options = Object.assign({ format: 'Shorts · 9:16', duration: 60, hero: 'Avtomatik', voice: 'O‘zbekcha — erkak', visualStyle: 'Kinematik, realistik', subtitles: 'O‘zbekcha', music: 'Mos fon musiqa' }, formOptions || {}); this.toast('Agentlar ishga tushmoqda…'); const result = await AgentPipeline.create(topic, options); const project = Object.assign({ id: `p_${Date.now()}`, title: result.director?.title || topic, format: options.format, duration: options.duration, hero: options.hero, voice: options.voice, visualStyle: options.visualStyle, subtitles: options.subtitles, music: options.music }, result); Store.setProject(project.id, project); this.renderStudio(project); this.showScreen('studio'); this.toast(result.demo ? 'Demo ssenariy tayyor' : 'Ssenariy va sahnalar tayyor'); }
  };
  root.SarideoUI = UI;
})(window);
